Section-2-22/pro/mysite/myapp/urls.py
from django.urls import path
from . import views


app_name = 'myapp'

urlpatterns = [
    path('',views.IndexClassView.as_view(),name='index'),
    # path('item/',views.item,name='item'),
    path('<int:pk>/',views.DetailClassView.as_view(), name='detail'),
    path('add/',views.ItemCreateView.as_view(), name='create-item'), 
    path('update/<int:pk>/',views.ItemUpdateView.as_view(), name='update-item'),
    path('delete/<int:pk>/',views.ItemDeleteView.as_view(), name='delete-item'),
]

Section-2-22/pro/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf.urls.static import static
from django.conf import settings
                                            

urlpatterns = [
    path('admin/', admin.site.urls),
    path('myapp/', include('myapp.urls')),
    path('users/', include('users.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

Section-2-22/pro/mysite/users/urls.py
from django.urls import path

from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [
    path('register/',views.register,name='register'),
    path('login/',auth_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/',views.logout_view,name='logout'),
    path('profile/',views.profile_view,name='profile'),
]

Section-2-22/pro/mysite/myapp/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

# Create your models here.


class Item(models.Model):

    def __str__(self):
        return self.item_name
    
    def get_absolute_url(self):
        return reverse('myapp:index')
    

    user_name = models.ForeignKey(User, on_delete=models.CASCADE,default=1)
    item_name = models.CharField(max_length=200)
    item_desc = models.CharField()
    item_price = models.IntegerField()
    item_image = models.CharField(max_length=500,default='https://cdn-icons-png.flaticon.com/512/1147/1147805.png')

Section-2-22/pro/mysite/users/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.


class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    image = models.ImageField(default='profilepic.jpg',upload_to='profile_pictures')
    location = models.CharField(max_length=100)


    def __str__(self):
        return self.user.username
    

    

Section-2-22/pro/mysite/myapp/forms.py
from django import forms
from .models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['item_name','item_desc','item_price','item_image']

        

Section-2-22/pro/mysite/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms

from django.contrib.auth.models import User

class RegisterForm(UserCreationForm):
    email = forms.EmailField()
    class Meta:
        model = User

        fields = ['username','email','password1','password2']

Section-2-22/pro/mysite/myapp/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Item
from .forms import ItemForm
from django.contrib.auth.decorators import login_required
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView , UpdateView , DeleteView
from django.urls import reverse_lazy


# Create your views here.

# @login_required
# def index(request):
#     item_list = Item.objects.all()
#     context = {
#         'item_list':item_list
#     }
#     # return HttpResponse(item_list)
#     return render(request,"myapp/index.html", context)


class IndexClassView(ListView):
    model = Item
    template_name = "myapp/index.html"
    context_object_name = 'item_list'
    



# @login_required
# def detail(request,id):
#     item = Item.objects.get(id=id)
#     context = {
#         'item':item
#     }
#     # return HttpResponse(f'This is the detail view for an item with id as {item}')
#     return render(request,"myapp/detail.html",context)


class DetailClassView(DetailView):
    model = Item
    template_name = "myapp/detail.html"
    context_object_name = 'item'




def item(request):
    return HttpResponse('<h1>This is an item!</h1>')

# @login_required
# def create_item(request):

#     form = ItemForm(request.POST or None)

#     if request.method=="POST":
#         if form.is_valid():
#             form.save()
#             return redirect('myapp:index')

#     context = {
#         'form':form,
#     }
#     return render(request,"myapp/item-form.html",context)


class ItemCreateView(CreateView):
    model = Item
    fields = ['item_name','item_desc','item_price','item_image']

    def form_valid(self,form):
        form.instance.user_name = self.request.user
        return super().form_valid(form)
    




# @login_required
# def update_item(request,id):
#     item = Item.objects.get(id=id)
#     form = ItemForm(request.POST or None,instance=item)

#     if form.is_valid():
#         form.save()
#         return redirect('myapp:index')


#     context = {
#         'form':form
#     }
#     return render(request,'myapp/item-form.html',context)


class ItemUpdateView(UpdateView):
    model = Item
    fields = ['item_name','item_desc','item_price','item_image']
    template_name_suffix = "_update_form"

    def get_queryset(self):
        return Item.objects.filter(user_name=self.request.user)




# @login_required
# def delete_item(request,id):

#     item = Item.objects.get(id=id)
#     if request.method=="POST":
#         item.delete()
#         return redirect('myapp:index')

#     return render(request,'myapp/item-delete.html')



class ItemDeleteView(DeleteView):
    model = Item
    success_url = reverse_lazy("myapp:index")

Section-2-22/pro/mysite/users/views.py
from django.shortcuts import render, redirect
# from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from .forms import RegisterForm
from django.contrib.auth import logout

from django.contrib.auth.decorators import login_required

def register(request):

    if request.method=="POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request,f'Welcome {username}, you have successfully logged in!')

            return redirect('login')
    
    form = RegisterForm()

    context = {
        'form':form
    }
    return render(request, 'users/register.html',context)



def logout_view(request):
    logout(request)
    return render(request, 'users/logout.html')

@login_required
def profile_view(request):
    return render(request, 'users/profile.html')

Section-2-22/pro/mysite/myapp/templates/myapp/base.html
 <!DOCTYPE html>
 <html lang="en">
 <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
    <title>BASE</title>
 </head>
 <body>
    <nav class="bg-blue-600 text-white">
        <div class="flex justify-between px-2 py-4 ">
            <a href="" class="font-bold text-2xl">Coffee & Co.</a>
            <div class="space-x-6">
                <a href="{% url 'profile' %}">Welcome, {{user.username}}</a>
                <!-- <a href="">Contact</a>
                <a href="">About Us</a> -->
                {% if user.is_authenticated %}
                    <a href="{% url 'profile' %}">Profile</a>
                    <a href="{% url 'logout' %}">Logout</a>

                {% else %}

                    <a href="{% url 'login' %}">Login</a>

                {% endif %}
            </div>
        </div>
    </nav>


    {% if messages %}
        {% for message in messages %}
            <div class="bg-green-500 text-green-700">{{message}}</div>  
        {% endfor %}
    {% endif %}

    {% block body %}

    {% endblock  %}
    
 </body>
 </html> 

Section-2-22/pro/mysite/myapp/templates/myapp/detail.html
{% extends 'myapp/base.html' %}
{% block body %}

    <div class="m-10 flex">

        <div>
            <img class="w-128 h-128 object-cover rounded-lg" src="{{item.item_image}}" alt="">

        </div>

        <div class="mx-16 space-y-5" >

            <div class="font-bold text-4xl">{{item.item_name}}</div>
            <div class="text-green-700 font-bold text-2xl">${{item.item_price}}</div>
            <div class=" text-2xl">{{item.item_desc}}</div>

            <div class="space-x-6">
                {% if item.user_name == request.user %}
                    <a class="bg-yellow-500 px-4 py-2 rounded-md font-bold text-white" href="{% url 'myapp:update-item' item.id %}">Edit</a>
                
                    <a class="bg-red-500 px-4 py-2 rounded-md font-bold text-white" href="{% url 'myapp:delete-item' item.id %}">Delete</a>
                {% endif %}
            </div>




        </div>

    </div>

    

    <button><a class="bg-blue-500 px-4 py-2 rounded-md font-bold text-white" href="{% url 'myapp:index' %}">
        Back
    </a></button>
    
{% endblock %}



<!-- <h1>{{ item.item_name }}</h1>
    <h1>{{ item.item_price }}</h1>
    <h1>{{ item.item_desc }}</h1> -->

Section-2-22/pro/mysite/myapp/templates/myapp/index.html
{% extends 'myapp/base.html' %}
{% block body %}

    <div>
        {% for item in item_list %}
        <div class="m-10 flex w-1/2 mx-auto">
            <div>
                <img class="w-64 h-64 object-cover rounded-lg" src="{{ item.item_image }}" alt="">


            </div>

            <div class="mx-16">
                <div class="font-bold">
                        {{item.item_name}}
                </div>
                <div>
                        {{item.item_desc}}
                </div>
                <div>
                        {{item.user_name}}
                </div>
                <div class="text-green-700 font-bold">
                        ${{item.item_price}}
                </div>
                

            </div>
            <div>
                        <a class="bg-red-500 text-white font-bold px-4 py-2 rounded-md" href="{% url 'myapp:detail' item.id %}">View Details</a>
                        
                </div>
        </div>
        {% endfor %}

        <a class="bg-yellow-500 px-4 py-2 rounded-md font-bold text-white" href="{% url 'myapp:create-item' %}">Add</a>
        

    </div>


    
 
{% endblock %}

Section-2-22/pro/mysite/myapp/templates/myapp/item-delete.html
{% extends 'myapp/base.html' %}
{% block body %}

<form method="POST">
    {% csrf_token %}
    <h2>Are you sure you want to delete the item?</h2>
    <button type="submit"><a class="bg-red-500 px-4 py-2 rounded-md font-bold text-white">Confirm</a></button>
</form>

{% endblock %}

Section-2-22/pro/mysite/myapp/templates/myapp/item-form.html
{% extends 'myapp/base.html' %}
{% block body %}
<form method="POST">
    {% csrf_token %}
    {{form}}
    <button type="submit"><a class="bg-green-500 px-4 py-2 rounded-md font-bold text-white" href="{% url 'myapp:index' %}">
        Save
    </a></button>
</form>
<br>

<button><a class="bg-blue-500 px-4 py-2 rounded-md font-bold text-white" href="{% url 'myapp:index' %}">
        Back
    </a></button>
{% endblock %}

Section-2-22/pro/mysite/myapp/templates/myapp/item_confirm_delete.html
{% extends 'myapp/base.html' %}
{% block body %}

<form method="POST">
    {% csrf_token %}
    <h2>Are you sure you want to delete the item?</h2>
    <button type="submit"><a class="bg-red-500 px-4 py-2 rounded-md font-bold text-white">Confirm</a></button>
</form>

{% endblock %}

Section-2-22/pro/mysite/myapp/templates/myapp/item_form.html
{% extends 'myapp/base.html' %}


{% block body %}

<div class="flex flex-col justify-center items-center min-h-screen p-10">
    <h1>Add Item</h1>
    <form method="POST" class="shadow-lg space-y-6 p-10 w-96">
        {% csrf_token %}

        {% for field in form %}

        <div>
            <label for="">{{field.label}}</label>
            <div class="border rounded p-2">{{field}}</div>
        </div>


        {% endfor %}

        <button class="bg-blue-500 text-white px-4 py-2 w-full">Register</button>

    </form>
</div>


{% endblock %}

<form method="POST">

    {% csrf_token %}
    {{form}}
    <button type="submit">Submit</button>
</form>


<!-- Passwords -->
<!-- karmanya,newproj@99 -->
<!-- karmanya11,passw@33 -->
<!-- newuser, newproj@99 -->

Section-2-22/pro/mysite/myapp/templates/myapp/item_update_form.html
<form method="POST">

    {% csrf_token %}

    {{form}}

    <input type="submit" name="" id="">

</form>

Section-2-22/pro/mysite/users/templates/users/login.html
{% extends 'myapp/base.html' %}

{% block body %}

<div class="flex flex-col justify-center items-center min-h-screen p-10">
    <h1>Login</h1>


<form method="POST" class="shadow-lg p-10 space-y-10">
    {% csrf_token %}

    {% if form.non_field_errors %}

    <div class="bg-red-500 text-white p-2">

        {% for error in form.non_field_errors %}

            <p>{{error}}</p>


        {% endfor %}
    </div>


    {% endif %}
        
    <div>
      <label for="">Username</label>
        <div class="border rounded p-2">{{form.username}}</div>
    </div>
    <div>
      <label for="">Password</label>
        <div class="border rounded p-2">{{form.password}}</div>
    </div>
    <button class="bg-blue-500 px-2 py-2 w-full text-white">Login</button>
</form>

</div>

{% endblock %}


<!-- 
<form method="POST">
    {% csrf_token %}
        {{form}}
    <button type="submit">Login</button>
</form> -->

Section-2-22/pro/mysite/users/templates/users/logout.html
<h2>You have been logged out!</h2>

Section-2-22/pro/mysite/users/templates/users/profile.html
<h2>{{user.username}}</h2>

<img src="{{user.profile.image.url}}" alt="">

Section-2-22/pro/mysite/users/templates/users/register.html
{% extends 'myapp/base.html' %}


{% block body %}

<div class="flex flex-col justify-center items-center min-h-screen p-10">
    <h1>Register</h1>
    <form method="POST" class="shadow-lg space-y-6 p-10 w-96">
        {% csrf_token %}

        {% for field in form %}

        <div>
            <label for="">{{field.label}}</label>
            <div class="border rounded p-2">{{field}}</div>
        </div>


        {% endfor %}

        <button class="bg-blue-500 text-white px-4 py-2 w-full">Register</button>

    </form>
</div>


{% endblock %}

<form method="POST">

    {% csrf_token %}
    {{form}}
    <button type="submit">Sign Up</button>
</form>


<!-- Passwords -->
<!-- karmanya,newproj@99 -->
<!-- karmanya11,passw@33 -->
<!-- newuser, newproj@99 -->